version: '3'
services:
  timchen-live-user-provider-docker-1:
    container_name: timchen-live-user-provider-docker-1
    image: 'timchen-live-user-provider-docker:1.0.4'
    ports:
      - "9091:9091"
    volumes:
      - D:\code\timchen-live-app-folder\logs\timchen-live-user-provider:/tmp/logs/timchen-live-user-provider
    environment:
      - TZ=Asia/Shanghai
      - DUBBO_IP_TO_REGISTRY=172.23.48.1
      - DUBBO_PORT_TO_REGISTRY=9091
      - DUBBO_PORT_TO_BIND=9091
      - JAVA_OPTS=-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms512m -Xmx512m -Xmn128m -Xss256k
    extra_hosts:
      - 'timchen.nacos.com:172.23.48.1'
      - 'timchen.db:172.23.48.1'
      - 'timchen.rmq.com:172.23.48.1'

  timchen-live-user-provider-docker-2:
    container_name: timchen-live-user-provider-docker-2
    image: 'timchen-live-user-provider-docker:1.0.4'
    ports:
      - "9092:9092"
    volumes:
      - D:\code\timchen-live-app-folder\logs\timchen-live-user-provider:/tmp/logs/timchen-live-user-provider
    environment:
      - TZ=Asia/Shanghai
      - DUBBO_IP_TO_REGISTRY=172.23.48.1
      - DUBBO_PORT_TO_REGISTRY=9092
      - DUBBO_PORT_TO_BIND=9092
      - JAVA_OPTS=-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms512m -Xmx512m -Xmn128m -Xss256k
    extra_hosts:
      - 'timchen.nacos.com:172.23.48.1'
      - 'timchen.db:172.23.48.1'
      - 'timchen.rmq.com:172.23.48.1'