spring:
  application:
    name: timchen-live-user-provider
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:timchen-db-sharding.yaml
    hikari:
      pool-name: timchen-user-pool
      minimum-idle: 15
      maximum-pool-size: 300
#      connection-init-sql: select 1
      connection-timeout: 4000
      max-lifetime: 600000
      idle-timeout: 60000
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      lettuce:
        pool:
          min-idle: 10
          max-idle: 20
          max-active: 50
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
    qos-port: 22222
  registry:
    address: nacos://localhost:8848?namespace=timchen-live-test&&username=timchen&&password=cxl123456
  protocol:
    name: dubbo
    port: -1
timchen:
  rmq:
    producer:
      name-srv: 127.0.0.1:9876
      group-name: ${spring.application.name}
      retry-times: 3
      send-time-out: 3000
    consumer:
      name-srv: 127.0.0.1:9876
      group-name: ${spring.application.name}