spring:
  application:
    name: timchen-live-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: timchen-live-api
          uri: lb://timchen-live-api
          predicates:
            - Path=/live/api/**

dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  registry:
    address: nacos://timchen.nacos.com:8848?namespace=timchen-live-test&&username=timchen&&password=cxl123456

logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO

timchen:
  gateway:
    notCheckUrlList:
      - /live/api/userLogin/
      - /live/api/living/list/